### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ban?autoReconnect=true&useSSL=false
    username: root
    password: fisher


server:
  port: 8090
#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: ban
  version: 0.1
  description: ban your mother
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    test-on-borrow: true
    validation-query: select 1
  rabbitmq:
    host: 204.48.17.119
    username: btc
    password: btc@123
#    virtual-host: /
    port: 5672